// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4iMCt5V921MiMLxPvl39wioYoDmi_X6U',
    appId: '1:109933873649:web:5ab194c0896f3c7bdbdc50',
    messagingSenderId: '109933873649',
    projectId: 'fir-10bba',
    authDomain: 'fir-10bba.firebaseapp.com',
    storageBucket: 'fir-10bba.appspot.com',
    measurementId: 'G-L0B5PM2GTZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxRM3mnUtQwTtzPWwuHCU22oADV4SxvVU',
    appId: '1:109933873649:android:2f865a9ce651b357dbdc50',
    messagingSenderId: '109933873649',
    projectId: 'fir-10bba',
    storageBucket: 'fir-10bba.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4iMCt5V921MiMLxPvl39wioYoDmi_X6U',
    appId: '1:109933873649:web:587b2ff25dc053addbdc50',
    messagingSenderId: '109933873649',
    projectId: 'fir-10bba',
    authDomain: 'fir-10bba.firebaseapp.com',
    storageBucket: 'fir-10bba.appspot.com',
    measurementId: 'G-4ZD49QZ40L',
  );

}